# Generated by Django 4.0.5 on 2023-01-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_user_info_one',
            name='string_date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
