# Generated by Django 4.0.5 on 2023-01-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_page', '0003_alter_get_user_info_one_string_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_user_info_one',
            name='string_phon_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
